### ISSUE TITLE
cannot import name 'MySqlDb' from 'notanorm' 

### ISSUE THREAD

**Issue by vinfun** [AtakamaLLC/notanorm#12]
Hi Dear Authors:

I have got a problem when trying to import MySqlDb, but sqlite is OK.

Could you please take a look, much Thanks.

from notanorm import MySqlDb

ImportError: cannot import name 'MySqlDb' from 'notanorm' (/home/userxxx/.miniconda3/lib/python3.9/site-packages/notanorm/__init__.py)

**Comment by earonesty** [comment]
I use `mysqlclient`, but `pymysql` works too.   notanorm doesn't proscribe which, but it is tested with `mysqlclient` only.

I will add to the README.  Thanks.

**Comment by vinfun** [comment]
> I use `mysqlclient`, but `pymysql` works too. `notanorm` doesn't proscribe which you have to use, but it is tested with `mysqlclient` only.
> 
> I will add to the README. Thanks.


OK, I will fork this and replace mysqlclient with pymysql. 
Thanks again

**Comment by earonesty** [comment]
no problem.   be aware:

mysqlclient - By far the fastest MySQL connector 
PyMySQL - use PyMySQL if: You can't use libmysqlclient for some reason. You want to use monkeypatched socket of gevent or eventlet.

a fork that supports both would be accepted upstream (try import mysqlclient ... try import the other!)

**Comment by earonesty** [comment]
hey would this work for you? 

https://github.com/AtakamaLLC/notanorm/pull/13

**Comment by vinfun** [comment]
> hey would this work for you?
> 
> #13
Recently I worked more overtime. So I use
try import mysqlclient ... try import pymysql 
to solve my problem for now.
Thank you for your kind answer and this issue can be closed now.
